repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: add-copyright
        name: add copyright header
        entry: python3 scripts/add_copyright.py
        language: system
        files: '\.(rs|py)$'

      - id: rust-format
        name: format rust files
        entry: rustfmt
        language: system
        pass_filenames: true
        files: '(^Cargo\.(toml|lock)$|\.rs$)'
