[package]
name = "rstu"
version.workspace = true
description = "Tools to process RST files"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
rstu_ast.workspace = true
rstu_parser.workspace = true
serde_json = "1"
